import type { Resource, Event, Business, Language, ResourceCategory, UserRole, Priority } from "./types";

// Import comprehensive Calgary resources database
import { 
  calgaryResources, 
  categoryGuides as calgaryGuides, 
  emergencyContacts as calgaryEmergencyContacts,
  winterSafetyTips as calgaryWinterTips 
} from "./calgary-resources";

// Re-export the comprehensive resources
export const resources = calgaryResources;
export const categoryGuides = calgaryGuides;

/**
 * Static UI strings translated into all 12 Calgary community languages.
 * Dynamic content (resource titles, descriptions) is handled at runtime
 * by the Google Translate hook in lib/translate.ts.
 */
export const translations: Record<string, Record<Language, string>> = {
  welcome: {
    en: "Everything Calgary.",
    pa: "ਹਰ ਕੁਝ ਕੈਲਗਰੀ।",
    tl: "Lahat ng Calgary.",
    zh: "卡爾加里的一切。",
    "zh-CN": "卡尔加里的一切。",
    es: "Todo Calgary.",
    uk: "Все про Калгарі.",
    ru: "Всё о Калгари.",
    am: "ሁሉም ካልጋሪ።",
    ar: "كل شيء كالجاري.",
    so: "Wax walba Calgary.",
    sw: "Kila kitu Calgary.",
  },
  onePlaceLine: {
    en: "One Place.",
    pa: "ਇੱਕ ਥਾਂ।",
    tl: "Isang Lugar.",
    zh: "一站式服務。",
    "zh-CN": "一站式服务。",
    es: "Un Solo Lugar.",
    uk: "Одне місце.",
    ru: "Одно место.",
    am: "አንድ ቦታ።",
    ar: "مكان واحد.",
    so: "Meel keliya.",
    sw: "Mahali pamoja.",
  },
  heroSubtitle: {
    en: "Find services, support, opportunities, programs, local businesses, community resources, and trusted guidance—without searching dozens of websites.",
    pa: "ਸੇਵਾਵਾਂ, ਸਹਾਇਤਾ, ਮੌਕੇ, ਪ੍ਰੋਗਰਾਮ, ਸਥਾਨਕ ਕਾਰੋਬਾਰ ਅਤੇ ਭਰੋਸੇਮੰਦ ਮਾਰਗਦਰਸ਼ਨ ਲੱਭੋ।",
    tl: "Maghanap ng mga serbisyo, suporta, oportunidad, programa, lokal na negosyo, at mga mapagkakatiwalaang gabay.",
    zh: "找到服務、支援、機會、計畫、本地商家和社區資源——無需搜尋數十個網站。",
    "zh-CN": "查找服务、支持、机会、项目、本地商家和社区资源——无需搜索数十个网站。",
    es: "Encuentre servicios, apoyo, oportunidades, programas, negocios locales y orientación confiable—sin buscar en docenas de sitios.",
    uk: "Знайдіть послуги, підтримку, можливості, програми та надійні ресурси — без пошуку на десятках сайтів.",
    ru: "Найдите услуги, поддержку, возможности, программы и надёжные ресурсы — без поиска на десятках сайтов.",
    am: "አገልግሎቶችን፣ ድጋፍን፣ ዕድሎችን፣ ፕሮግራሞችን እና የማህበረሰብ ሀብቶችን ያግኙ።",
    ar: "اعثر على الخدمات والدعم والفرص والبرامج والموارد المجتمعية—دون البحث في عشرات المواقع.",
    so: "Hel adeegyada, taageerada, fursadaha, barnaamijyada, ganacsiyada maxalliga ah iyo tilmaamaha la믿aamanka.",
    sw: "Pata huduma, msaada, fursa, programu, biashara za ndani na mwongozo wa kuaminika—bila kutafuta tovuti nyingi.",
  },
  getStarted: {
    en: "Get Started",
    pa: "ਸ਼ੁਰੂ ਕਰੋ",
    tl: "Magsimula",
    zh: "開始使用",
    "zh-CN": "开始使用",
    es: "Comenzar",
    uk: "Почати",
    ru: "Начать",
    am: "ጀምር",
    ar: "ابدأ الآن",
    so: "Bilow",
    sw: "Anza",
  },
  askAI: {
    en: "Askonnect — Ask me.",
    pa: "Askonnect — ਮੈਨੂੰ ਪੁੱਛੋ।",
    tl: "Askonnect — Magtanong sa akin.",
    zh: "Askonnect — 問我吧。",
    "zh-CN": "Askonnect — 问我吧。",
    es: "Askonnect — Pregúntame.",
    uk: "Askonnect — Запитайте мене.",
    ru: "Askonnect — Спросите меня.",
    am: "Askonnect — ጠይቁኝ።",
    ar: "Askonnect — اسألني.",
    so: "Askonnect — Ii weydii.",
    sw: "Askonnect — Niulize.",
  },
  home: {
    en: "Home",
    pa: "ਮੁੱਖ ਪੰਨਾ",
    tl: "Home",
    zh: "首頁",
    "zh-CN": "首页",
    es: "Inicio",
    uk: "Головна",
    ru: "Главная",
    am: "መነሻ",
    ar: "الرئيسية",
    so: "Guriga",
    sw: "Nyumbani",
  },
  explore: {
    en: "Explore",
    pa: "ਖੋਜੋ",
    tl: "I-explore",
    zh: "探索",
    "zh-CN": "探索",
    es: "Explorar",
    uk: "Досліджувати",
    ru: "Исследовать",
    am: "ያስሱ",
    ar: "استكشف",
    so: "Sahami",
    sw: "Chunguza",
  },
  aiGuide: {
    en: "Askonnect",
    pa: "Askonnect",
    tl: "Askonnect",
    zh: "Askonnect",
    "zh-CN": "Askonnect",
    es: "Askonnect",
    uk: "Askonnect",
    ru: "Askonnect",
    am: "Askonnect",
    ar: "Askonnect",
    so: "Askonnect",
    sw: "Askonnect",
  },
  shortlist: {
    en: "Shortlist",
    pa: "ਸ਼ਾਰਟਲਿਸਟ",
    tl: "Shortlist",
    zh: "收藏夾",
    "zh-CN": "收藏夹",
    es: "Favoritos",
    uk: "Список",
    ru: "Список",
    am: "አጭር ዝርዝር",
    ar: "المفضلة",
    so: "Liiska Gaaban",
    sw: "Orodha Fupi",
  },
  profile: {
    en: "Profile",
    pa: "ਪ੍ਰੋਫਾਈਲ",
    tl: "Profile",
    zh: "個人資料",
    "zh-CN": "个人资料",
    es: "Perfil",
    uk: "Профіль",
    ru: "Профиль",
    am: "መገለጫ",
    ar: "الملف الشخصي",
    so: "Astaan",
    sw: "Wasifu",
  },
  emergency: {
    en: "Emergency Hub",
    pa: "ਐਮਰਜੈਂਸੀ ਹੱਬ",
    tl: "Emergency Hub",
    zh: "緊急中心",
    "zh-CN": "紧急中心",
    es: "Centro de Emergencia",
    uk: "Центр екстреної допомоги",
    ru: "Экстренный центр",
    am: "የድንገተኛ ማዕከል",
    ar: "مركز الطوارئ",
    so: "Xarunta Degdegga",
    sw: "Kituo cha Dharura",
  },
  resources: {
    en: "Resources",
    pa: "ਸਰੋਤ",
    tl: "Mga Mapagkukunan",
    zh: "資源",
    "zh-CN": "资源",
    es: "Recursos",
    uk: "Ресурси",
    ru: "Ресурсы",
    am: "ሀብቶች",
    ar: "الموارد",
    so: "Kheyraadka",
    sw: "Rasilimali",
  },
  businesses: {
    en: "Businesses",
    pa: "ਕਾਰੋਬਾਰ",
    tl: "Mga Negosyo",
    zh: "商家",
    "zh-CN": "商家",
    es: "Negocios",
    uk: "Підприємства",
    ru: "Бизнесы",
    am: "ንግዶች",
    ar: "الشركات",
    so: "Ganacsiyada",
    sw: "Biashara",
  },
  community: {
    en: "Community",
    pa: "ਭਾਈਚਾਰਾ",
    tl: "Komunidad",
    zh: "社區",
    "zh-CN": "社区",
    es: "Comunidad",
    uk: "Громада",
    ru: "Сообщество",
    am: "ማህበረሰብ",
    ar: "المجتمع",
    so: "Bulshada",
    sw: "Jamii",
  },
  rentshield: {
    en: "RentShield",
    pa: "RentShield",
    tl: "RentShield",
    zh: "RentShield",
    "zh-CN": "RentShield",
    es: "RentShield",
    uk: "RentShield",
    ru: "RentShield",
    am: "RentShield",
    ar: "RentShield",
    so: "RentShield",
    sw: "RentShield",
  },
  selectLanguage: {
    en: "Select your language",
    pa: "ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ",
    tl: "Piliin ang iyong wika",
    zh: "選擇您的語言",
    "zh-CN": "选择您的语言",
    es: "Seleccione su idioma",
    uk: "Оберіть мову",
    ru: "Выберите язык",
    am: "ቋንቋዎን ይምረጡ",
    ar: "اختر لغتك",
    so: "Dooro luqadaada",
    sw: "Chagua lugha yako",
  },
};

export const categoryLabels: Record<ResourceCategory, Record<Language, string>> = {
  housing: {
    en: "Housing", pa: "ਰਿਹਾਇਸ਼", tl: "Pabahay", zh: "住房", "zh-CN": "住房",
    es: "Vivienda", uk: "Житло", ru: "Жильё", am: "መኖሪያ", ar: "السكن", so: "Guriyeynta", sw: "Makazi",
  },
  jobs: {
    en: "Jobs", pa: "ਨੌਕਰੀਆਂ", tl: "Trabaho", zh: "工作", "zh-CN": "工作",
    es: "Empleos", uk: "Робота", ru: "Работа", am: "ስራዎች", ar: "الوظائف", so: "Shaqooyinka", sw: "Kazi",
  },
  food: {
    en: "Food Support", pa: "ਭੋਜਨ ਸਹਾਇਤਾ", tl: "Tulong Pagkain", zh: "食品援助", "zh-CN": "食品援助",
    es: "Apoyo Alimentario", uk: "Продовольча допомога", ru: "Продовольственная помощь",
    am: "የምግብ ድጋፍ", ar: "دعم الغذاء", so: "Taageerada Cuntada", sw: "Msaada wa Chakula",
  },
  "mental-health": {
    en: "Mental Health", pa: "ਮਾਨਸਿਕ ਸਿਹਤ", tl: "Kalusugang Pangkaisipan", zh: "心理健康", "zh-CN": "心理健康",
    es: "Salud Mental", uk: "Психічне здоров'я", ru: "Психическое здоровье",
    am: "የአዕምሮ ጤና", ar: "الصحة النفسية", so: "Caafimaadka Maskaxda", sw: "Afya ya Akili",
  },
  healthcare: {
    en: "Healthcare", pa: "ਸਿਹਤ ਸੇਵਾ", tl: "Pangangalagang Pangkalusugan", zh: "醫療保健", "zh-CN": "医疗保健",
    es: "Salud", uk: "Охорона здоров'я", ru: "Здравоохранение",
    am: "ጤና አጠባበቅ", ar: "الرعاية الصحية", so: "Daryeelka Caafimaadka", sw: "Huduma ya Afya",
  },
  newcomer: {
    en: "Newcomer Services", pa: "ਨਵੇਂ ਆਉਣ ਵਾਲਿਆਂ ਦੀਆਂ ਸੇਵਾਵਾਂ", tl: "Serbisyo para sa Bagong Dating",
    zh: "新移民服務", "zh-CN": "新移民服务", es: "Servicios para Recién Llegados",
    uk: "Послуги для новоприбулих", ru: "Услуги для новоприбывших",
    am: "አዲስ የመጡ አገልግሎቶች", ar: "خدمات القادمين الجدد", so: "Adeegyada Cusub", sw: "Huduma za Wageni Wapya",
  },
  family: {
    en: "Family Services", pa: "ਪਰਿਵਾਰਕ ਸੇਵਾਵਾਂ", tl: "Serbisyo para sa Pamilya",
    zh: "家庭服務", "zh-CN": "家庭服务", es: "Servicios Familiares",
    uk: "Сімейні послуги", ru: "Семейные услуги",
    am: "የቤተሰብ አገልግሎቶች", ar: "خدمات الأسرة", so: "Adeegyada Qoyska", sw: "Huduma za Familia",
  },
  senior: {
    en: "Senior Services", pa: "ਬਜ਼ੁਰਗਾਂ ਦੀਆਂ ਸੇਵਾਵਾਂ", tl: "Serbisyo para sa Nakatatanda",
    zh: "老年服務", "zh-CN": "老年服务", es: "Servicios para Mayores",
    uk: "Послуги для літніх", ru: "Услуги для пожилых",
    am: "የሽማግሌ አገልግሎቶች", ar: "خدمات كبار السن", so: "Adeegyada Waayeelka", sw: "Huduma za Wazee",
  },
  disability: {
    en: "Disability Support", pa: "ਅਪੰਗਤਾ ਸਹਾਇਤਾ", tl: "Suporta sa May Kapansanan",
    zh: "殘障支持", "zh-CN": "残障支持", es: "Apoyo a Discapacitados",
    uk: "Підтримка людей з інвалідністю", ru: "Поддержка людей с инвалидностью",
    am: "ለአካል ጉዳተኞች ድጋፍ", ar: "دعم ذوي الاحتياجات الخاصة", so: "Taageerada Naafada", sw: "Msaada wa Ulemavu",
  },
  transit: {
    en: "Transit", pa: "ਆਵਾਜਾਈ", tl: "Transportasyon", zh: "交通", "zh-CN": "交通",
    es: "Transporte", uk: "Транспорт", ru: "Транспорт",
    am: "ትራንዚት", ar: "النقل", so: "Gaadhi-mareenka", sw: "Usafiri",
  },
  education: {
    en: "Education", pa: "ਸਿੱਖਿਆ", tl: "Edukasyon", zh: "教育", "zh-CN": "教育",
    es: "Educación", uk: "Освіта", ru: "Образование",
    am: "ትምህርት", ar: "التعليم", so: "Waxbarashada", sw: "Elimu",
  },
  legal: {
    en: "Legal Help", pa: "ਕਾਨੂੰਨੀ ਸਹਾਇਤਾ", tl: "Tulong Legal", zh: "法律幫助", "zh-CN": "法律帮助",
    es: "Ayuda Legal", uk: "Юридична допомога", ru: "Юридическая помощь",
    am: "ህጋዊ እርዳታ", ar: "المساعدة القانونية", so: "Gargaarka Sharciga", sw: "Msaada wa Kisheria",
  },
  business: {
    en: "Small Business", pa: "ਛੋਟਾ ਕਾਰੋਬਾਰ", tl: "Maliit na Negosyo", zh: "小型企業", "zh-CN": "小型企业",
    es: "Pequeñas Empresas", uk: "Малий бізнес", ru: "Малый бизнес",
    am: "አነስተኛ ንግድ", ar: "الشركات الصغيرة", so: "Ganacsiga Yar", sw: "Biashara Ndogo",
  },
  volunteering: {
    en: "Volunteering", pa: "ਵਲੰਟੀਅਰਿੰਗ", tl: "Pag-volunteer", zh: "志願服務", "zh-CN": "志愿服务",
    es: "Voluntariado", uk: "Волонтерство", ru: "Волонтёрство",
    am: "በጎ ፈቃደኝነት", ar: "التطوع", so: "Taladaarka", sw: "Kujitolea",
  },
  emergency: {
    en: "Emergency", pa: "ਐਮਰਜੈਂਸੀ", tl: "Emergency", zh: "緊急情況", "zh-CN": "紧急情况",
    es: "Emergencia", uk: "Надзвичайна ситуація", ru: "Чрезвычайная ситуация",
    am: "ድንገተኛ", ar: "الطوارئ", so: "Xaaladda Degdegga", sw: "Dharura",
  },
  community: {
    en: "Community", pa: "ਭਾਈਚਾਰਾ", tl: "Komunidad", zh: "社區", "zh-CN": "社区",
    es: "Comunidad", uk: "Громада", ru: "Сообщество",
    am: "ማህበረሰብ", ar: "المجتمع", so: "Bulshada", sw: "Jamii",
  },
  lgbtq: {
    en: "LGBTQ+ Support", pa: "LGBTQ+ ਸਹਾਇਤਾ", tl: "LGBTQ+ Support", zh: "LGBTQ+ 支持", "zh-CN": "LGBTQ+ 支持",
    es: "Apoyo LGBTQ+", uk: "Підтримка LGBTQ+", ru: "Поддержка LGBTQ+",
    am: "LGBTQ+ ድጋፍ", ar: "دعم LGBTQ+", so: "Taageerada LGBTQ+", sw: "Msaada wa LGBTQ+",
  },
  indigenous: {
    en: "Indigenous Support", pa: "ਦੇਸੀ ਸਹਾਇਤਾ", tl: "Indigenous Support", zh: "原住民支持", "zh-CN": "原住民支持",
    es: "Apoyo Indígena", uk: "Підтримка корінних народів", ru: "Поддержка коренных народов",
    am: "የተወላጆች ድጋፍ", ar: "دعم السكان الأصليين", so: "Taageerada Asaasiga", sw: "Msaada wa Wenyeji",
  },
  youth: {
    en: "Youth", pa: "ਨੌਜਵਾਨ", tl: "Kabataan", zh: "青年", "zh-CN": "青年",
    es: "Juventud", uk: "Молодь", ru: "Молодёжь",
    am: "ወጣቶች", ar: "الشباب", so: "Dhalinyarada", sw: "Vijana",
  },
  arts: {
    en: "Arts & Culture", pa: "ਕਲਾ ਅਤੇ ਸੱਭਿਆਚਾਰ", tl: "Sining at Kultura", zh: "藝術與文化", "zh-CN": "艺术和文化",
    es: "Artes y Cultura", uk: "Мистецтво та культура", ru: "Искусство и культура",
    am: "ጥበብ እና ባህል", ar: "الفنون والثقافة", so: "Fanka iyo Dhaqanka", sw: "Sanaa na Utamaduni",
  },
  logistics: {
    en: "Shipping & Logistics", pa: "ਸ਼ਿਪਿੰਗ ਅਤੇ ਲੌਜਿਸਟਿਕਸ", tl: "Pagpapadala at Logistik",
    zh: "運輸與物流", "zh-CN": "运输与物流", es: "Envíos y Logística",
    uk: "Доставка та логістика", ru: "Доставка и логистика",
    am: "ሽፋን እና ሎጂስቲክስ", ar: "الشحن والخدمات اللوجستية", so: "Raritaanka iyo Xididdada", sw: "Usafirishaji na Usambazaji",
  },
  tourism: {
    en: "Tourists & Visitors", pa: "ਸੈਲਾਨੀ ਅਤੇ ਮਹਿਮਾਨ", tl: "Turista at Bisita",
    zh: "遊客與訪客", "zh-CN": "游客与访客", es: "Turistas y Visitantes",
    uk: "Туристи та відвідувачі", ru: "Туристы и посетители",
    am: "ቱሪስቶች እና ጎብኚዎች", ar: "السياح والزوار", so: "Dalxiisayaasha iyo Martida", sw: "Watalii na Wageni",
  },
  workspace: {
    en: "Workspaces", pa: "ਵਰਕਸਪੇਸ", tl: "Mga Workspace", zh: "辦公空間", "zh-CN": "办公空间",
    es: "Espacios de Trabajo", uk: "Робочі простори", ru: "Рабочие пространства",
    am: "የስራ ቦታዎች", ar: "مساحات العمل", so: "Goobaha Shaqada", sw: "Maeneo ya Kazi",
  },
  storage: {
    en: "Storage Facilities", pa: "ਸਟੋਰੇਜ ਸਹੂਲਤਾਂ", tl: "Mga Storage", zh: "倉儲設施", "zh-CN": "仓储设施",
    es: "Almacenamiento", uk: "Складські приміщення", ru: "Складские помещения",
    am: "የማከማቻ ተቋሞች", ar: "مرافق التخزين", so: "Xarumaha Kaydinta", sw: "Vifaa vya Kuhifadhi",
  },
  "ethnic-market": {
    en: "Cultural & Ethnic Stores", pa: "ਸੱਭਿਆਚਾਰਕ ਸਟੋਰ", tl: "Cultural at Ethnic na Tindahan",
    zh: "文化與民族商店", "zh-CN": "文化与民族商店", es: "Tiendas Culturales y Étnicas",
    uk: "Культурні та етнічні магазини", ru: "Культурные и этнические магазины",
    am: "የባህል ሱቆች", ar: "المتاجر الثقافية والعرقية", so: "Dukaammada Dhaqanka", sw: "Maduka ya Kitamaduni",
  },
  "farmers-market": {
    en: "Farmers Markets", pa: "ਕਿਸਾਨ ਮੰਡੀ", tl: "Farmers Market", zh: "農夫市場", "zh-CN": "农夫市场",
    es: "Mercados de Agricultores", uk: "Фермерські ринки", ru: "Фермерские рынки",
    am: "የገበሬ ገበያዎች", ar: "أسواق المزارعين", so: "Suuqyada Beeralayda", sw: "Masoko ya Wakulima",
  },
  essentials: {
    en: "Local Essentials", pa: "ਸਥਾਨਕ ਜ਼ਰੂਰੀ ਸੇਵਾਵਾਂ", tl: "Mga Lokal na Serbisyo",
    zh: "本地必需服務", "zh-CN": "本地必需服务", es: "Servicios Esenciales Locales",
    uk: "Місцеві необхідні послуги", ru: "Местные необходимые услуги",
    am: "አካባቢያዊ አስፈላጊ አገልግሎቶች", ar: "الخدمات المحلية الأساسية", so: "Adeegyada Muhiimka ah ee Maxalliga", sw: "Huduma Muhimu za Ndani",
  },
};

export const languageNames: Record<Language, string> = {
  en: "English",
  pa: "ਪੰਜਾਬੀ",
  tl: "Filipino",
  zh: "廣東話",
  "zh-CN": "普通话",
  es: "Español",
  uk: "Українська",
  ru: "Русский",
  am: "አማርኛ",
  ar: "العربية",
  so: "Soomaali",
  sw: "Kiswahili",
};

export const roleLabels: Record<UserRole, Record<Language, string>> = {
  newcomer: {
    en: "Newcomer", pa: "ਨਵਾਂ ਆਇਆ", tl: "Bagong Dating", zh: "新移民", "zh-CN": "新移民",
    es: "Recién Llegado", uk: "Новоприбулий", ru: "Новоприбывший",
    am: "አዲስ የመጣ", ar: "قادم جديد", so: "Qof Cusub", sw: "Mwanzo",
  },
  senior: {
    en: "Senior", pa: "ਬਜ਼ੁਰਗ", tl: "Senior", zh: "老年人", "zh-CN": "老年人",
    es: "Mayor", uk: "Літній", ru: "Пожилой",
    am: "ሽማግሌ", ar: "كبير السن", so: "Waayeel", sw: "Mzee",
  },
  business: {
    en: "Business Owner", pa: "ਕਾਰੋਬਾਰੀ", tl: "May-ari ng Negosyo", zh: "企業主", "zh-CN": "企业主",
    es: "Dueño de Negocio", uk: "Підприємець", ru: "Предприниматель",
    am: "የንግድ ባለቤት", ar: "صاحب عمل", so: "Milkiilaha Ganacsiga", sw: "Mmiliki wa Biashara",
  },
  ngo: {
    en: "NGO/Non-Profit", pa: "NGO/ਗੈਰ-ਮੁਨਾਫ਼ਾ", tl: "NGO/Non-Profit", zh: "非營利組織", "zh-CN": "非营利组织",
    es: "ONG/Sin fines de lucro", uk: "НГО/Некомерційна", ru: "НКО/Некоммерческая",
    am: "ኤን.ጂ.ኦ/ትርፋ-አልባ", ar: "منظمة غير ربحية", so: "NGO/Aan Faa'iido lahayn", sw: "NGO/Isiyo ya Faida",
  },
  creator: {
    en: "Content Creator", pa: "ਕੰਟੈਂਟ ਕ੍ਰਿਏਟਰ", tl: "Content Creator", zh: "內容創作者", "zh-CN": "内容创作者",
    es: "Creador de Contenido", uk: "Контент-мейкер", ru: "Контент-мейкер",
    am: "ይዘት ፈጣሪ", ar: "منشئ محتوى", so: "Abuuraha Xogta", sw: "Muundaji wa Maudhui",
  },
  family: {
    en: "Family", pa: "ਪਰਿਵਾਰ", tl: "Pamilya", zh: "家庭", "zh-CN": "家庭",
    es: "Familia", uk: "Сім'я", ru: "Семья",
    am: "ቤተሰብ", ar: "عائلة", so: "Qoys", sw: "Familia",
  },
  student: {
    en: "Student", pa: "ਵਿਦਿਆਰਥੀ", tl: "Estudyante", zh: "學生", "zh-CN": "学生",
    es: "Estudiante", uk: "Студент", ru: "Студент",
    am: "ተማሪ", ar: "طالب", so: "Arday", sw: "Mwanafunzi",
  },
};

export const priorityLabels: Record<Priority, Record<Language, string>> = categoryLabels;

export const uiText: Record<string, Record<Language, string>> = {
  search: {
    en: "Search resources...", pa: "ਸਰੋਤ ਖੋਜੋ...", tl: "Maghanap ng mga mapagkukunan...",
    zh: "搜尋資源...", "zh-CN": "搜索资源...", es: "Buscar recursos...",
    uk: "Пошук ресурсів...", ru: "Поиск ресурсов...",
    am: "ሀብቶችን ፈልግ...", ar: "البحث عن الموارد...", so: "Raadi kheyraadka...", sw: "Tafuta rasilimali...",
  },
  save: {
    en: "Save", pa: "ਸੁਰੱਖਿਅਤ ਕਰੋ", tl: "I-save", zh: "儲存", "zh-CN": "保存",
    es: "Guardar", uk: "Зберегти", ru: "Сохранить",
    am: "አስቀምጥ", ar: "حفظ", so: "Keydi", sw: "Hifadhi",
  },
  call: {
    en: "Call", pa: "ਕਾਲ ਕਰੋ", tl: "Tumawag", zh: "致電", "zh-CN": "拨打",
    es: "Llamar", uk: "Зателефонувати", ru: "Позвонить",
    am: "ደውል", ar: "اتصل", so: "Wac", sw: "Piga simu",
  },
  directions: {
    en: "Directions", pa: "ਦਿਸ਼ਾਵਾਂ", tl: "Direksyon", zh: "路線", "zh-CN": "路线",
    es: "Direcciones", uk: "Маршрут", ru: "Маршрут",
    am: "አቅጣጫዎች", ar: "الاتجاهات", so: "Jihooyinka", sw: "Maelekezo",
  },
  website: {
    en: "Website", pa: "ਵੈੱਬਸਾਈਟ", tl: "Website", zh: "網站", "zh-CN": "网站",
    es: "Sitio Web", uk: "Вебсайт", ru: "Веб-сайт",
    am: "ዌብሳይት", ar: "الموقع", so: "Websaydka", sw: "Tovuti",
  },
  noResults: {
    en: "No resources found", pa: "ਕੋਈ ਸਰੋਤ ਨਹੀਂ ਮਿਲਿਆ", tl: "Walang nahanap na mapagkukunan",
    zh: "未找到資源", "zh-CN": "未找到资源", es: "No se encontraron recursos",
    uk: "Ресурси не знайдено", ru: "Ресурсы не найдены",
    am: "ምንም ሀብቶች አልተገኙም", ar: "لم يتم العثور على موارد", so: "Kheyraad lama helin", sw: "Hakuna rasilimali zilizopatikana",
  },
  typeMessage: {
    en: "Ask Askonnect anything...", pa: "Askonnect ਨੂੰ ਕੁਝ ਵੀ ਪੁੱਛੋ...",
    tl: "Magtanong kay Askonnect...", zh: "向 Askonnect 提問...", "zh-CN": "向 Askonnect 提问...",
    es: "Pregunta a Askonnect...", uk: "Запитайте Askonnect...", ru: "Спросите Askonnect...",
    am: "Askonnect ን ምንም ይጠይቁ...", ar: "اسأل Askonnect...", so: "Wax kasta u weydii Askonnect...", sw: "Uliza Askonnect chochote...",
  },
  emptyShortlist: {
    en: "Your shortlist is empty", pa: "ਤੁਹਾਡੀ ਸ਼ਾਰਟਲਿਸਟ ਖਾਲੀ ਹੈ", tl: "Walang laman ang iyong shortlist",
    zh: "您的收藏夾為空", "zh-CN": "您的收藏夹为空", es: "Tu lista está vacía",
    uk: "Ваш список порожній", ru: "Ваш список пуст",
    am: "አጭር ዝርዝርዎ ባዶ ነው", ar: "قائمتك فارغة", so: "Liiskaagu waa madhan yahay", sw: "Orodha yako fupi ni tupu",
  },
  emptyShortlistHint: {
    en: "Tap the heart icon on any resource to save it here",
    pa: "ਕਿਸੇ ਵੀ ਸਰੋਤ 'ਤੇ ਦਿਲ ਆਈਕਨ ਟੈਪ ਕਰੋ",
    tl: "I-tap ang heart icon sa anumang resource para i-save dito",
    zh: "點擊任何資源上的心形圖標將其保存", "zh-CN": "点击任何资源上的心形图标将其保存",
    es: "Toca el ícono del corazón en cualquier recurso para guardarlo",
    uk: "Натисніть на іконку серця, щоб зберегти ресурс", ru: "Нажмите на иконку сердца, чтобы сохранить ресурс",
    am: "ሀብቱን ለማስቀመጥ የልብ አዶን ይጫኑ", ar: "اضغط على أيقونة القلب لحفظ أي مورد",
    so: "Riix calaamadda wadnaha si aad u keydinayso kheyraadka", sw: "Gusa ikoni ya moyo kwenye rasilimali yoyote kuihifadhi hapa",
  },
};

// Resources are imported from calgary-resources.ts
export const events: Event[] = [
  {
    id: "1",
    title: "Newcomer Welcome Night",
    description: "Monthly gathering for new immigrants to meet community members and learn about Calgary resources.",
    date: "2024-02-15",
    time: "6:00 PM - 9:00 PM",
    location: "Calgary Central Library",
    category: "meetup",
  },
  {
    id: "2",
    title: "Resume Writing Workshop",
    description: "Learn how to create a Canadian-style resume with tips from HR professionals.",
    date: "2024-02-18",
    time: "2:00 PM - 4:00 PM",
    location: "Bow Valley College",
    category: "workshop",
  },
  {
    id: "3",
    title: "Lunar New Year Festival",
    description: "Celebrate the Year of the Dragon with performances, food, and cultural activities.",
    date: "2024-02-10",
    time: "11:00 AM - 6:00 PM",
    location: "Calgary Chinatown",
    category: "cultural",
  },
  {
    id: "4",
    title: "Food Bank Volunteer Day",
    description: "Help sort and pack food hampers for families in need.",
    date: "2024-02-20",
    time: "9:00 AM - 12:00 PM",
    location: "Calgary Food Bank",
    category: "volunteering",
  },
  {
    id: "5",
    title: "Small Business Startup Bootcamp",
    description: "Intensive workshop on starting a business in Alberta. Covers permits, taxes, and funding.",
    date: "2024-02-25",
    time: "9:00 AM - 5:00 PM",
    location: "Business Link Alberta",
    category: "training",
  },
];

export const businesses: Business[] = [
  {
    id: "1",
    name: "Calgary Halal Meats",
    description: "Family-owned halal butcher serving Calgary for over 20 years.",
    category: "Grocery",
    address: "1234 17 Avenue SE, Calgary",
    phone: "403-555-0123",
    offers: ["10% off for newcomers"],
    verified: true,
  },
  {
    id: "2",
    name: "Tina's Filipino Kitchen",
    description: "Authentic Filipino cuisine in the heart of Calgary.",
    category: "Restaurant",
    address: "567 Centre Street NW, Calgary",
    phone: "403-555-0456",
    website: "https://tinasfilipinokitchen.ca",
    offers: ["Free lumpia with any order over $30"],
    verified: true,
  },
  {
    id: "3",
    name: "Global Tax Services",
    description: "Tax preparation services for newcomers and small businesses.",
    category: "Professional Services",
    address: "890 8 Avenue SW, Calgary",
    phone: "403-555-0789",
    offers: ["Free consultation for first-time clients"],
    verified: true,
  },
];

export const emergencyContacts = calgaryEmergencyContacts;
export const winterSafetyTips = calgaryWinterTips;

/** AI suggestion prompts — English only; displayed text goes through useTranslation */
export const aiSuggestions: string[] = [
  "How do I find affordable housing?",
  "What are my tenant rights?",
  "Help me find a family doctor",
  "How do I get a transit pass?",
  "Register for ESL classes",
  "Find job training programs",
];
