import type { Resource, Event, Business, Language, ResourceCategory, UserRole, Priority } from "./types";

// Import comprehensive Calgary resources database
import { 
  calgaryResources, 
  categoryGuides as calgaryGuides, 
  emergencyContacts as calgaryEmergencyContacts,
  winterSafetyTips as calgaryWinterTips 
} from "./calgary-resources";

// Re-export the comprehensive resources
export const resources = calgaryResources;
export const categoryGuides = calgaryGuides;

export const translations: Record<string, Record<Language, string>> = {
  welcome: {
    en: "Everything Calgary.",
    fr: "Tout Calgary.",
    tl: "Lahat ng Calgary.",
    es: "Todo Calgary.",
    ar: "كل كالجاري.",
    zh: "卡尔加里的一切。",
  },
  onePlaceLine: {
    en: "One Place.",
    fr: "Un Seul Endroit.",
    tl: "Isang Lugar.",
    es: "Un Solo Lugar.",
    ar: "مكان واحد.",
    zh: "一站式服务。",
  },
  heroSubtitle: {
    en: "Find services, support, opportunities, programs, local businesses, community resources, and trusted guidance—without searching dozens of websites.",
    fr: "Trouvez des services, du soutien, des opportunités, des programmes, des entreprises locales, des ressources communautaires et des conseils fiables—sans chercher sur des dizaines de sites.",
    tl: "Maghanap ng mga serbisyo, suporta, oportunidad, programa, lokal na negosyo, at mga mapagkakatiwalaang gabay—nang hindi naghahanap sa maraming website.",
    es: "Encuentre servicios, apoyo, oportunidades, programas, negocios locales, recursos comunitarios y orientación confiable—sin buscar en docenas de sitios.",
    ar: "اعثر على الخدمات والدعم والفرص والبرامج والشركات المحلية والموارد المجتمعية والإرشادات الموثوقة—دون البحث في عشرات المواقع.",
    zh: "查找服务、支持、机会、项目、本地商家、社区资源和可信指导——无需搜索数十个网站。",
  },
  getStarted: {
    en: "Get Started",
    fr: "Commencer",
    tl: "Magsimula",
    es: "Comenzar",
    ar: "ابدأ الآن",
    zh: "开始使用",
  },
  askAI: {
    en: "Ask Calgary Bridge AI",
    fr: "Demandez à Calgary Bridge AI",
    tl: "Magtanong sa Calgary Bridge AI",
    es: "Preguntar a Calgary Bridge AI",
    ar: "اسأل Calgary Bridge AI",
    zh: "询问 Calgary Bridge AI",
  },
  home: {
    en: "Home",
    fr: "Accueil",
    tl: "Home",
    es: "Inicio",
    ar: "الرئيسية",
    zh: "首页",
  },
  explore: {
    en: "Explore",
    fr: "Explorer",
    tl: "I-explore",
    es: "Explorar",
    ar: "استكشف",
    zh: "探索",
  },
  aiGuide: {
    en: "AI Guide",
    fr: "Guide IA",
    tl: "AI Guide",
    es: "Guía IA",
    ar: "دليل AI",
    zh: "AI 指南",
  },
  shortlist: {
    en: "Shortlist",
    fr: "Favoris",
    tl: "Shortlist",
    es: "Favoritos",
    ar: "المفضلة",
    zh: "收藏夹",
  },
  profile: {
    en: "Profile",
    fr: "Profil",
    tl: "Profile",
    es: "Perfil",
    ar: "الملف الشخصي",
    zh: "个人资料",
  },
  emergency: {
    en: "Emergency Hub",
    fr: "Centre d'urgence",
    tl: "Emergency Hub",
    es: "Centro de Emergencia",
    ar: "مركز الطوارئ",
    zh: "紧急中心",
  },
  resources: {
    en: "Resources",
    fr: "Ressources",
    tl: "Mga Mapagkukunan",
    es: "Recursos",
    ar: "الموارد",
    zh: "资源",
  },
  businesses: {
    en: "Businesses",
    fr: "Entreprises",
    tl: "Mga Negosyo",
    es: "Negocios",
    ar: "الشركات",
    zh: "商家",
  },
  community: {
    en: "Community",
    fr: "Communauté",
    tl: "Komunidad",
    es: "Comunidad",
    ar: "المجتمع",
    zh: "社区",
  },
  rentshield: {
    en: "RentShield",
    fr: "RentShield",
    tl: "RentShield",
    es: "RentShield",
    ar: "RentShield",
    zh: "租房保护",
  },
};

export const categoryLabels: Record<ResourceCategory, Record<Language, string>> = {
  housing: {
    en: "Housing",
    fr: "Logement",
    tl: "Pabahay",
    es: "Vivienda",
    ar: "السكن",
    zh: "住房",
  },
  jobs: {
    en: "Jobs",
    fr: "Emplois",
    tl: "Trabaho",
    es: "Empleos",
    ar: "الوظائف",
    zh: "工作",
  },
  food: {
    en: "Food Support",
    fr: "Aide Alimentaire",
    tl: "Tulong Pagkain",
    es: "Apoyo Alimentario",
    ar: "دعم الغذاء",
    zh: "食品援助",
  },
  "mental-health": {
    en: "Mental Health",
    fr: "Santé Mentale",
    tl: "Kalusugang Pangkaisipan",
    es: "Salud Mental",
    ar: "الصحة النفسية",
    zh: "心理健康",
  },
  healthcare: {
    en: "Healthcare",
    fr: "Soins de Santé",
    tl: "Pangangalagang Pangkalusugan",
    es: "Salud",
    ar: "الرعاية الصحية",
    zh: "医疗保健",
  },
  newcomer: {
    en: "Newcomer Services",
    fr: "Services aux Nouveaux Arrivants",
    tl: "Serbisyo para sa Bagong Dating",
    es: "Servicios para Recién Llegados",
    ar: "خدمات القادمين الجدد",
    zh: "新移民服务",
  },
  family: {
    en: "Family Services",
    fr: "Services aux Familles",
    tl: "Serbisyo para sa Pamilya",
    es: "Servicios Familiares",
    ar: "خدمات الأسرة",
    zh: "家庭服务",
  },
  senior: {
    en: "Senior Services",
    fr: "Services aux Aînés",
    tl: "Serbisyo para sa Nakatatanda",
    es: "Servicios para Mayores",
    ar: "خدمات كبار السن",
    zh: "老年服务",
  },
  disability: {
    en: "Disability Support",
    fr: "Soutien aux Personnes Handicapées",
    tl: "Suporta sa May Kapansanan",
    es: "Apoyo a Discapacitados",
    ar: "دعم ذوي الاحتياجات الخاصة",
    zh: "残障支持",
  },
  transit: {
    en: "Transit",
    fr: "Transport",
    tl: "Transportasyon",
    es: "Transporte",
    ar: "النقل",
    zh: "交通",
  },
  education: {
    en: "Education",
    fr: "Éducation",
    tl: "Edukasyon",
    es: "Educación",
    ar: "التعليم",
    zh: "教育",
  },
  legal: {
    en: "Legal Help",
    fr: "Aide Juridique",
    tl: "Tulong Legal",
    es: "Ayuda Legal",
    ar: "المساعدة القانونية",
    zh: "法律帮助",
  },
  business: {
    en: "Small Business",
    fr: "Petites Entreprises",
    tl: "Maliit na Negosyo",
    es: "Pequeñas Empresas",
    ar: "الشركات الصغيرة",
    zh: "小型企业",
  },
  volunteering: {
    en: "Volunteering",
    fr: "Bénévolat",
    tl: "Pag-volunteer",
    es: "Voluntariado",
    ar: "التطوع",
    zh: "志愿服务",
  },
  emergency: {
    en: "Emergency",
    fr: "Urgence",
    tl: "Emergency",
    es: "Emergencia",
    ar: "الطوارئ",
    zh: "紧急情况",
  },
  community: {
    en: "Community",
    fr: "Communauté",
    tl: "Komunidad",
    es: "Comunidad",
    ar: "المجتمع",
    zh: "社区",
  },
  lgbtq: {
    en: "LGBTQ+ Support",
    fr: "Soutien LGBTQ+",
    tl: "LGBTQ+ Support",
    es: "Apoyo LGBTQ+",
    ar: "دعم LGBTQ+",
    zh: "LGBTQ+ 支持",
  },
  indigenous: {
    en: "Indigenous Support",
    fr: "Soutien aux Autochtones",
    tl: "Indigenous Support",
    es: "Apoyo Indígena",
    ar: "دعم السكان الأصليين",
    zh: "土著支持",
  },
  youth: {
    en: "Youth",
    fr: "Jeunesse",
    tl: "Kabataan",
    es: "Juventud",
    ar: "الشباب",
    zh: "青年",
  },
  arts: {
    en: "Arts & Culture",
    fr: "Arts et Culture",
    tl: "Sining at Kultura",
    es: "Artes y Cultura",
    ar: "الفنون والثقافة",
    zh: "艺术和文化",
  },
};

export const languageNames: Record<Language, string> = {
  en: "English",
  fr: "Français",
  tl: "Tagalog",
  es: "Español",
  ar: "العربية",
  zh: "中文",
};

export const roleLabels: Record<UserRole, Record<Language, string>> = {
  newcomer: {
    en: "Newcomer",
    fr: "Nouvel arrivant",
    tl: "Bagong Dating",
    es: "Recién Llegado",
    ar: "قادم جديد",
    zh: "新移民",
  },
  senior: {
    en: "Senior",
    fr: "Aîné",
    tl: "Senior",
    es: "Mayor",
    ar: "كبير السن",
    zh: "老年人",
  },
  business: {
    en: "Business Owner",
    fr: "Propriétaire d'entreprise",
    tl: "May-ari ng Negosyo",
    es: "Dueño de Negocio",
    ar: "صاحب عمل",
    zh: "企业主",
  },
  ngo: {
    en: "NGO/Non-Profit",
    fr: "ONG/Sans but lucratif",
    tl: "NGO/Non-Profit",
    es: "ONG/Sin fines de lucro",
    ar: "منظمة غير ربحية",
    zh: "非营利组织",
  },
  creator: {
    en: "Content Creator",
    fr: "Créateur de contenu",
    tl: "Content Creator",
    es: "Creador de Contenido",
    ar: "منشئ محتوى",
    zh: "内容创作者",
  },
  family: {
    en: "Family",
    fr: "Famille",
    tl: "Pamilya",
    es: "Familia",
    ar: "عائلة",
    zh: "家庭",
  },
  student: {
    en: "Student",
    fr: "Étudiant",
    tl: "Estudyante",
    es: "Estudiante",
    ar: "طالب",
    zh: "学生",
  },
};

export const priorityLabels: Record<Priority, Record<Language, string>> = categoryLabels;

export const uiText: Record<string, Record<Language, string>> = {
  search: {
    en: "Search resources...",
    fr: "Rechercher des ressources...",
    tl: "Maghanap ng mga mapagkukunan...",
    es: "Buscar recursos...",
    ar: "البحث عن الموارد...",
    zh: "搜索资源...",
  },
  save: {
    en: "Save",
    fr: "Enregistrer",
    tl: "I-save",
    es: "Guardar",
    ar: "حفظ",
    zh: "保存",
  },
  call: {
    en: "Call",
    fr: "Appeler",
    tl: "Tumawag",
    es: "Llamar",
    ar: "اتصل",
    zh: "拨打",
  },
  directions: {
    en: "Directions",
    fr: "Itinéraire",
    tl: "Direksyon",
    es: "Direcciones",
    ar: "الاتجاهات",
    zh: "路线",
  },
  website: {
    en: "Website",
    fr: "Site Web",
    tl: "Website",
    es: "Sitio Web",
    ar: "الموقع",
    zh: "网站",
  },
  noResults: {
    en: "No resources found",
    fr: "Aucune ressource trouvée",
    tl: "Walang nahanap na mapagkukunan",
    es: "No se encontraron recursos",
    ar: "لم يتم العثور على موارد",
    zh: "未找到资源",
  },
  markDone: {
    en: "Mark as done",
    fr: "Marquer comme terminé",
    tl: "Markahan bilang tapos",
    es: "Marcar como hecho",
    ar: "وضع علامة كمكتمل",
    zh: "标记为完成",
  },
  addNote: {
    en: "Add a note...",
    fr: "Ajouter une note...",
    tl: "Magdagdag ng note...",
    es: "Añadir una nota...",
    ar: "أضف ملاحظة...",
    zh: "添加备注...",
  },
  emptyShortlist: {
    en: "Your shortlist is empty",
    fr: "Votre liste est vide",
    tl: "Walang laman ang iyong shortlist",
    es: "Tu lista está vacía",
    ar: "قائمتك فارغة",
    zh: "您的收藏夹为空",
  },
  emptyShortlistHint: {
    en: "Tap the heart icon on any resource to save it here",
    fr: "Appuyez sur l'icône cœur pour enregistrer ici",
    tl: "I-tap ang heart icon sa anumang resource para i-save dito",
    es: "Toca el ícono del corazón en cualquier recurso para guardarlo aquí",
    ar: "اضغط على أيقونة القلب في أي مورد لحفظه هنا",
    zh: "点击任何资源上的心形图标将其保存到这里",
  },
  typeMessage: {
    en: "Ask Calgary Bridge AI...",
    fr: "Demandez à Calgary Bridge AI...",
    tl: "Magtanong sa Calgary Bridge AI...",
    es: "Pregunta a Calgary Bridge AI...",
    ar: "اسأل Calgary Bridge AI...",
    zh: "向 Calgary Bridge AI 提问...",
  },
  aiWelcome: {
    en: "Hello! I'm Calgary Bridge AI, your personal guide to Calgary's services and resources. How can I help you today?",
    fr: "Bonjour! Je suis Calgary Bridge AI, votre guide personnel pour les services de Calgary. Comment puis-je vous aider?",
    tl: "Kumusta! Ako si Calgary Bridge AI, ang iyong personal na gabay sa mga serbisyo ng Calgary. Paano kita matutulungan ngayon?",
    es: "¡Hola! Soy Calgary Bridge AI, tu guía personal de servicios de Calgary. ¿Cómo puedo ayudarte hoy?",
    ar: "مرحبا! أنا Calgary Bridge AI، دليلك الشخصي لخدمات كالجاري. كيف يمكنني مساعدتك اليوم؟",
    zh: "你好！我是 Calgary Bridge AI，您的卡尔加里服务和资源个人指南。今天我能帮您什么？",
  },
  emergencyTitle: {
    en: "Emergency Hub",
    fr: "Centre d'urgence",
    tl: "Emergency Hub",
    es: "Centro de Emergencia",
    ar: "مركز الطوارئ",
    zh: "紧急中心",
  },
  emergencySubtitle: {
    en: "Critical contacts and winter safety",
    fr: "Contacts critiques et sécurité hivernale",
    tl: "Mahalagang kontak at kaligtasan sa taglamig",
    es: "Contactos críticos y seguridad invernal",
    ar: "جهات الاتصال الحرجة والسلامة الشتوية",
    zh: "紧急联系人和冬季安全",
  },
  winterSafety: {
    en: "Winter Safety Tips",
    fr: "Conseils de sécurité hivernale",
    tl: "Mga Tip sa Kaligtasan sa Taglamig",
    es: "Consejos de Seguridad Invernal",
    ar: "نصائح السلامة الشتوية",
    zh: "冬季安全提示",
  },
  forYou: {
    en: "For You",
    fr: "Pour Vous",
    tl: "Para Sa Iyo",
    es: "Para Ti",
    ar: "لك",
    zh: "为您推荐",
  },
  allResources: {
    en: "All Resources",
    fr: "Toutes les Ressources",
    tl: "Lahat ng Mapagkukunan",
    es: "Todos los Recursos",
    ar: "جميع الموارد",
    zh: "所有资源",
  },
  featured: {
    en: "Featured",
    fr: "En Vedette",
    tl: "Tampok",
    es: "Destacado",
    ar: "مميز",
    zh: "精选",
  },
  selectLanguage: {
    en: "Select your language",
    fr: "Sélectionnez votre langue",
    tl: "Piliin ang iyong wika",
    es: "Seleccione su idioma",
    ar: "اختر لغتك",
    zh: "选择您的语言",
  },
  selectRole: {
    en: "I am a...",
    fr: "Je suis un(e)...",
    tl: "Ako ay isang...",
    es: "Soy un(a)...",
    ar: "أنا...",
    zh: "我是...",
  },
  selectPriorities: {
    en: "What matters most to you?",
    fr: "Qu'est-ce qui compte le plus pour vous?",
    tl: "Ano ang pinakamahalaga sa iyo?",
    es: "¿Qué es lo que más te importa?",
    ar: "ما الأهم بالنسبة لك؟",
    zh: "对您来说最重要的是什么？",
  },
  next: {
    en: "Next",
    fr: "Suivant",
    tl: "Susunod",
    es: "Siguiente",
    ar: "التالي",
    zh: "下一步",
  },
  back: {
    en: "Back",
    fr: "Retour",
    tl: "Bumalik",
    es: "Atrás",
    ar: "رجوع",
    zh: "返回",
  },
  finish: {
    en: "Get Started",
    fr: "Commencer",
    tl: "Magsimula",
    es: "Comenzar",
    ar: "ابدأ الآن",
    zh: "开始使用",
  },
  allSet: {
    en: "You're all set!",
    fr: "Vous êtes prêt!",
    tl: "Handa ka na!",
    es: "¡Todo listo!",
    ar: "أنت جاهز!",
    zh: "您已准备就绪！",
  },
  personalizedExperience: {
    en: "We've personalized Calgary Connect just for you.",
    fr: "Nous avons personnalisé Calgary Connect pour vous.",
    tl: "Na-personalize namin ang Calgary Connect para sa iyo.",
    es: "Hemos personalizado Calgary Connect solo para ti.",
    ar: "لقد خصصنا Calgary Connect من أجلك.",
    zh: "我们已为您个性化定制了 Calgary Connect。",
  },
};

// Resources are now imported from calgary-resources.ts (see top of file)
// The comprehensive database includes 60+ real Calgary resources with:
// - Real phone numbers, addresses, and websites
// - Eligibility information
// - Services offered
// - Category guides with first steps

export const events: Event[] = [
  {
    id: "1",
    title: "Newcomer Welcome Night",
    description: "Monthly gathering for new immigrants to meet community members and learn about Calgary resources.",
    date: "2024-02-15",
    time: "6:00 PM - 9:00 PM",
    location: "Calgary Central Library",
    category: "meetup",
  },
  {
    id: "2",
    title: "Resume Writing Workshop",
    description: "Learn how to create a Canadian-style resume with tips from HR professionals.",
    date: "2024-02-18",
    time: "2:00 PM - 4:00 PM",
    location: "Bow Valley College",
    category: "workshop",
  },
  {
    id: "3",
    title: "Lunar New Year Festival",
    description: "Celebrate the Year of the Dragon with performances, food, and cultural activities.",
    date: "2024-02-10",
    time: "11:00 AM - 6:00 PM",
    location: "Calgary Chinatown",
    category: "cultural",
  },
  {
    id: "4",
    title: "Food Bank Volunteer Day",
    description: "Help sort and pack food hampers for families in need.",
    date: "2024-02-20",
    time: "9:00 AM - 12:00 PM",
    location: "Calgary Food Bank",
    category: "volunteering",
  },
  {
    id: "5",
    title: "Small Business Startup Bootcamp",
    description: "Intensive workshop on starting a business in Alberta. Covers permits, taxes, and funding.",
    date: "2024-02-25",
    time: "9:00 AM - 5:00 PM",
    location: "Business Link Alberta",
    category: "training",
  },
];

export const businesses: Business[] = [
  {
    id: "1",
    name: "Calgary Halal Meats",
    description: "Family-owned halal butcher serving Calgary for over 20 years.",
    category: "Grocery",
    address: "1234 17 Avenue SE, Calgary",
    phone: "403-555-0123",
    offers: ["10% off for newcomers"],
    verified: true,
  },
  {
    id: "2",
    name: "Tina's Filipino Kitchen",
    description: "Authentic Filipino cuisine in the heart of Calgary.",
    category: "Restaurant",
    address: "567 Centre Street NW, Calgary",
    phone: "403-555-0456",
    website: "https://tinasfilipinokitchen.ca",
    offers: ["Free lumpia with any order over $30"],
    verified: true,
  },
  {
    id: "3",
    name: "Global Tax Services",
    description: "Tax preparation services for newcomers and small businesses.",
    category: "Professional Services",
    address: "890 8 Avenue SW, Calgary",
    phone: "403-555-0789",
    offers: ["Free consultation for first-time clients"],
    verified: true,
  },
];

// Use enhanced emergency contacts from calgary-resources.ts
export const emergencyContacts = calgaryEmergencyContacts;

export const winterSafetyTips = calgaryWinterTips;

export const aiSuggestions = [
  {
    en: "How do I find affordable housing?",
    fr: "Comment trouver un logement abordable?",
    tl: "Paano ako makakahanap ng abot-kayang tirahan?",
    es: "¿Cómo encuentro vivienda asequible?",
    ar: "كيف أجد سكنًا بأسعار معقولة؟",
    zh: "如何找到经济适用房？",
  },
  {
    en: "What are my tenant rights?",
    fr: "Quels sont mes droits en tant que locataire?",
    tl: "Ano ang aking mga karapatan bilang nangungupahan?",
    es: "¿Cuáles son mis derechos como inquilino?",
    ar: "ما هي حقوقي كمستأجر؟",
    zh: "我作为租户有哪些权利？",
  },
  {
    en: "Help me find a family doctor",
    fr: "Aidez-moi à trouver un médecin de famille",
    tl: "Tulungan akong maghanap ng family doctor",
    es: "Ayúdame a encontrar un médico familiar",
    ar: "ساعدني في العثور على طبيب عائلة",
    zh: "帮我找一位家庭医生",
  },
  {
    en: "How do I get a transit pass?",
    fr: "Comment obtenir un titre de transport?",
    tl: "Paano ako makakakuha ng transit pass?",
    es: "¿Cómo obtengo un pase de transporte?",
    ar: "كيف أحصل على تذ��رة نقل؟",
    zh: "如何获得交通卡？",
  },
  {
    en: "Register for ESL classes",
    fr: "S'inscrire aux cours d'ALS",
    tl: "Mag-enroll sa ESL classes",
    es: "Inscribirse en clases de ESL",
    ar: "التسجيل في دورات اللغة الإنجليزية",
    zh: "报名英语课程",
  },
  {
    en: "Find job training programs",
    fr: "Trouver des programmes de formation professionnelle",
    tl: "Maghanap ng job training programs",
    es: "Encontrar programas de capacitación laboral",
    ar: "البحث عن برامج التدريب المهني",
    zh: "寻找职业培训项目",
  },
];
